// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDs91F0yOaRjSP3Yb7JrnYz5BUmGocWrq4',
    appId: '1:348529831299:web:5ffeeb02badba569d19ab6',
    messagingSenderId: '348529831299',
    projectId: 'login-c2dcc',
    authDomain: 'login-c2dcc.firebaseapp.com',
    storageBucket: 'login-c2dcc.appspot.com',
    measurementId: 'G-6J87L1N79Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyALHnsxr7sklLOUu7VbldfQ7SaNy6Hr0zw',
    appId: '1:348529831299:android:0812b8d1132cc2dcd19ab6',
    messagingSenderId: '348529831299',
    projectId: 'login-c2dcc',
    storageBucket: 'login-c2dcc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDy5HDRo957G79qN1nok4p-yZVOzaRExuo',
    appId: '1:348529831299:ios:d7bca7ab2557bd09d19ab6',
    messagingSenderId: '348529831299',
    projectId: 'login-c2dcc',
    storageBucket: 'login-c2dcc.appspot.com',
    androidClientId: '348529831299-3ko41v109upetvetcefn5p3alok5jg9v.apps.googleusercontent.com',
    iosClientId: '348529831299-5li09kjo7u537rg69b51m1vnjb5ho91n.apps.googleusercontent.com',
    iosBundleId: 'com.example.travelui',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDy5HDRo957G79qN1nok4p-yZVOzaRExuo',
    appId: '1:348529831299:ios:d7bca7ab2557bd09d19ab6',
    messagingSenderId: '348529831299',
    projectId: 'login-c2dcc',
    storageBucket: 'login-c2dcc.appspot.com',
    androidClientId: '348529831299-3ko41v109upetvetcefn5p3alok5jg9v.apps.googleusercontent.com',
    iosClientId: '348529831299-5li09kjo7u537rg69b51m1vnjb5ho91n.apps.googleusercontent.com',
    iosBundleId: 'com.example.travelui',
  );
}
